apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nacos
  namespace: default
spec:
  entryPoints:
    - web-nacos
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: nacos-service
          port: 8848
