apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nexus
  namespace: default
spec:
  entryPoints:
    - web-nexus
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: nexus3
          port: 8081
